### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by fastchain** [botlabsDev/npkpy#4]
Hello,

Npks from latest stable release are unpackable with npkpy 

```
npkpy --files system-6.48.4.npk  --show-container
Traceback (most recent call last):
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/bin/npkpy", line 8, in <module>
    sys.exit(main())
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/npkpy/main.py", line 47, in main
    analyse_npk(opts, files)
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/npkpy/analyse_npk.py", line 13, in analyse_npk
    for file in npk_files:
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/npkpy/main.py", line 46, in <genexpr>
    files = (Npk(f) for f in (opts.files if opts.files else get_all_nkp_files(opts.src_folder, opts.glob)))
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/npkpy/npk/npk.py", line 35, in __init__
    self.pck_header = self.pck_cnt_list[0]
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/npkpy/npk/npk.py", line 74, in pck_cnt_list
    self.__cnt_list = self.__parse_all_cnt()
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/npkpy/npk/npk.py", line 81, in __parse_all_cnt
    lst.append(self.__get_cnt(offset))
  File "/home/afx/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/npkpy/npk/npk.py", line 94, in __get_cnt
    return CNT_HANDLER[cnt_id](data, offset)
TypeError: 'str' object is not callable
(tmp)  ✘  afx@proton  /mnt/iso  
```

Am I doing something wrong?

Thank you!

**Comment by botlabsDev** [comment]
You did nothing wrong here. MikroTik started using a new package id in their npk format which npkpy couldn't parse. I pushed a fix and released a new PyPi version. 

Thanks for opening this issue :)
